### ISSUE TITLE
Redo SGML once SLW Mod Loader gets into a somewhat functioning state?

### ISSUE THREAD

**Issue by GoldtexTwitch** [GoldtexTwitch/Sonic-Generations-Mod-Loader#1]
I've noticed that SLW Mod Loader is being redone. Should I continue on working on this despite SLW Mod Loader's remake or should I restart this once SLW Mod Loader is functioning?

**Comment by GoldtexTwitch** [comment]
(pinging @Radfordhound)

**Comment by Radfordhound** [comment]
Don't worry about it.. I'll merge all my SLW mod loader changes with your GML changes once the re-write's complete. :)

**Comment by Radfordhound** [comment]
They should be relatively easy to integrate too, provided I write this in an extendable-enough way (which is the plan).

**Comment by GoldtexTwitch** [comment]
Okay. I also just thought of something. Wouldn't this repo be un-necessary after the remake though? I do imagine Generatons support being added in during the remake.

**Comment by Radfordhound** [comment]
It depends on if you think it makes more sense to merge them both into a single program or keep them separate to be honest. :P Personally I see pros and cons for both..

**Comment by Radfordhound** [comment]
Although to be honest it would be super awesome to merge these changes into the LW mod loader and support both.

**Comment by GoldtexTwitch** [comment]
Yeah, I think it would be nice for SLW Mod Loader to support Gens as well. Maybe if Unleashed gets ported we can add Unleashed functionality as well.

**Comment by GoldtexTwitch** [comment]
That's if Unleashed ever gets ported to PC. I'm doubting that it will, but if it does, cool!

**Comment by GoldtexTwitch** [comment]
I'm hoping that SGML gets merged into SLWML while it's going through a rewrite. Gonna close this since there's not really anything being talked about this.
